### ISSUE TITLE
some important typographical errors

### ISSUE THREAD

**Issue by ihsanhacioglu** [ng2-ui/ng2-ui#1]
There are some important typographical errors on pages "https://www.npmjs.com/package/jsvalley-ui" and "https://github.com/jsvalley/jsvalley-ui"

Wrong | Corrected
------------ | -------------
$ npm install javalley-ui | $ npm install jsvalley-ui
$ npm instlal ng2-map | $ npm install ng2-map

**Comment by allenhwkim** [comment]
Thanks. I will fix it immediately
