### ISSUE TITLE
DatetimePicket errors out when the value is removed from input element

### ISSUE THREAD

**Issue by charles5557** [ng2-ui/ng2-ui#15]
Hi,

I wonder if this is an intended behavior. I created an input element with datetimepicker attached to it.
It works beautifully until I cleared out the value in the input element. The js errors out and the datetimepicker display is completely off. I wonder if there is a scenario dealing with null value maybe?

thanks

**Comment by allenhwkim** [comment]
Thanks, I will treat this as a bug

**Comment by allenhwkim** [comment]
fixed
