### ISSUE TITLE
ng2-overlay error

### ISSUE THREAD

**Issue by haisaco** [ng2-ui/ng2-ui#16]
When I install ng2-ui and import lib in AngularModule have error:
GET http://localhost:3000/ng2-overlay 404 (Not Found)
please help me!

**Comment by allenhwkim** [comment]
Thanks for trying this module.

Please uninstall and install `ng2-ui` module.

If that does not work, please follow examples in this repo.
https://github.com/ng2-ui/ng2-ui/blob/master/app

https://github.com/ng2-ui/ng2-ui/blob/master/app/systemjs.config.js
https://github.com/ng2-ui/ng2-ui/blob/master/app/main.ts


There must be a reason related to node_modules and/or configuration
