### ISSUE TITLE
cannot find definition file for 'googlemaps'

### ISSUE THREAD

**Issue by kiebor** [ng2-ui/ng2-ui#21]
/// < reference types="googlemaps" >

Typescript error: cannot find definition file for 'googlemaps'

Exception thrown on transpile for:
info-window.d.ts
geo-coder.d.ts

EDIT: actually all map directives and components present this error.

I have searched the downloaded directories for all ng2-* locations added via npm install for ng2-ui and can't see the defintion file to point it at.

Am I missing a file/package/dependency?

**Comment by allenhwkim** [comment]
Let me check. It must have dependency of types/@googlemaps.

**Comment by kiebor** [comment]
i didnt clone the repo, but installed into my project via reference in my package.json... So, i'm not sure where the typings should live for this bundle. According to the documentation it should be ok in devdependencies.

Manually referencing @types/googlemaps from my package.json in either fixes the problem locally for me.

For a published package, I'd expect a transpiler with typings in devdependencies would also suffice. 

Perhaps just write this up as a FAQ workaround as no one else seems to have had the same issue.

**Comment by kiebor** [comment]
having said that, it seems logical to me that because the type defs are directly referenced by the typescripts files, there should be a relative path for < reference types=" "  >. The ref points to a global or static path, not a relative location in the package directory.

let me play with that as it seems the simplest and most likely fix

**Comment by kiebor** [comment]
Placing @types/googlemaps in my package.json under dev dependencies fixed the issue because it makes the google.d.ts globally available to my project.

I think just put a note on your Readme that users need to include it in their local configuration (like the angular team do with Hammer for material if they experience trouble.

**Comment by allenhwkim** [comment]
This has been fixed.
