### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by Wychell** [ng2-ui/ng2-ui#22]
Exception: Call to Node module failed with error: ReferenceError: window is not defined
at new Ng2MapComponent (C:\path\node_modules\ng2-map\dist\ng2-map.umd.js:147:9)

I'm using the component, when I load the page I get this error
*ng2-map

**Comment by allenhwkim** [comment]
Is it compile error?, or run time error?

**Comment by Wychell** [comment]
Is it compile error!

**Comment by allenhwkim** [comment]
Could you add screenshot here with a plunker example?
I have fixed compile time error, but it seems runtime error is not possible because it's run on a browser. `window` must be always there AFAIK.

**Comment by Wychell** [comment]
I'm using the version of angular / cli 2.0 with the stupid visial template, when implementing the angular component 2.4 works perfectly


http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/

**Comment by allenhwkim** [comment]
Visual Studio? hmmm, no comment 😑

**Comment by Wychell** [comment]
Really --'
